#pragma once

namespace driftless {

// ONNX Runtime wrapper for the same weights android/.../fusion/VelocityModel.kt
// loads as TFLite -- one training/ checkpoint, two runtimes.
//
// CONTRACT (see models/MODEL_CONTRACT.md, generated by the export):
//   file    models/velocity_model.onnx, self-contained (no .onnx.data sidecar)
//   input   "imu_window"  [batch, 14, 80] float32, channels-FIRST.
//           Note this is the TRANSPOSE of the TFLite layout, which is
//           channels-last. Feeding the wrong one does not error, it returns
//           nonsense.
//   output  "speed_dpsi"  [batch, 3] float32:
//             [0] speed_ms   mean forward speed over the interval, m/s
//             [1] dpsi_rad   heading change across the interval, rad
//             [2] dv_ms      change in speed across the interval, m/s
//
// 80 samples at 10 Hz = 8 s of causal context; the prediction covers the final
// 2 s. Normalisation is baked into the graph: feed raw SI units, read SI units.
//
// [0] is what UkfFusionEngine::updateVelocityModel consumes. [1] is the more
// accurate of the two heads and is not yet wired anywhere.
class VelocityModel {
public:
    VelocityModel() = default;
    // TODO: Ort::Session over models/velocity_model.onnx
};

}  // namespace driftless
