"""Golden fixture pinning the edge engine's feature builder to this pipeline.

The C++ edge engine reimplements `imu_derived` and assembles the model's
[1, 14, 80] input itself, from a FOG stream that has no CSV columns to read
channel names off. Nothing in either codebase forces the two to agree: the
model takes any 14xN float tensor and returns three plausible-looking numbers
for it, so a channel in the wrong slot produces confident nonsense rather than
an error.

This writes real accelerometer/gyroscope samples together with the feature rows
THIS pipeline derives from them, so the C++ can assert equality instead of
assuming it.

WHICH CHANNELS ARE PINNED. Slots 0-5 and 9-13 are pinned exactly. Slots 6-8
(grav_*) are deliberately not: in training they hold the phone dataset's own
GRAVITY column, and a FOG has no such thing, so the edge engine substitutes its
causal attitude estimate. That substitution is sound -- rotation augmentation
rotates the gravity triple as a physical vector, so the model saw gravity
pointing in many directions with magnitude ~9.8, which is what the estimate
provides -- but it is not bit-comparable, so the fixture checks only that the
vector is physically plausible.

THE GYRO SLOTS ARE THE POINT. Feature slots 3/4/5 are named for the phone
dataset's raw column order (gyro_yaw, gyro_pitch, gyro_roll), which is NOT the
physical x/y/z order. The physical mapping is x->3, y->5, z->4 -- see
GYRO_XYZ_COLUMNS and augment.GYRO_XYZ_IDX. Writing physical xyz straight into
3/4/5 puts the vertical-axis rate, the single most informative channel, where
the model learned to read a horizontal one.

Runtime-agnostic on purpose: it is plain JSON of inputs and expected feature
rows, so the C++ engine and the Android app can both assert against the same
reference instead of each trusting its own reading of the channel table. Both
have already got that reading wrong, in two different ways.

Run:  python -m driftless_train.edge_fixture
Out:  training/artifacts/models/model_window_golden.json
      -> copied into both consumer trees by `--copy-to-consumers`
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from .augment import ACC_XYZ_IDX, GRAV_XYZ_IDX, GYRO_XYZ_IDX
from .dataset import DT, PROC_DIR
from .paths import MODEL_DIR
from .preprocess import FEATURE_CHANNELS, _causal_gravity, imu_derived

N_SAMPLES = 100          # > 80, so the last rows form a complete window
# Canonical home is next to the exports: the fixture is part of the model
# contract, not a property of either consumer, and BOTH runtimes need it.
# `to_tflite.py --copy-to-consumers` distributes it alongside MODEL_CONTRACT.md,
# the same way the model itself reaches them.
OUT_PATH = MODEL_DIR / "model_window_golden.json"


def build(run_path: Path, n: int = N_SAMPLES, start: int = 0) -> dict:
    """Take real samples, derive the features cold, and record both.

    Cold on purpose: the engine starts its gravity filter from its first sample
    with y[0] = x[0], so the reference must start the same way for the two to be
    comparable at all. This is why the fixture carries its own expected values
    rather than slicing them out of the training arrays, whose filter state
    carries in from earlier in the run.
    """
    with np.load(run_path) as z:
        feats = z["features"].astype(np.float64)
    rows = feats[start:start + n]
    if len(rows) < n:
        raise ValueError(f"{run_path.name}: only {len(rows)} rows from {start}")

    # Physical 3-vectors, in true x/y/z order -- what a FOG hands the engine.
    accel = rows[:, ACC_XYZ_IDX]
    gyro = rows[:, GYRO_XYZ_IDX]

    grav = _causal_gravity(accel, DT)
    derived = imu_derived(accel, gyro, DT, grav_fallback=rows[:, GRAV_XYZ_IDX])

    expected = np.empty((n, len(FEATURE_CHANNELS)), dtype=np.float64)
    expected[:, ACC_XYZ_IDX] = accel
    expected[:, GYRO_XYZ_IDX] = gyro          # x->3, y->5, z->4, NOT 3/4/5
    expected[:, GRAV_XYZ_IDX] = grav          # informational; not asserted
    for name, col in derived.items():
        expected[:, FEATURE_CHANNELS.index(name)] = col

    return {
        "_comment": "Generated by `python -m driftless_train.edge_fixture`. "
                    "Do not hand-edit.",
        "source_run": run_path.stem,
        "start_index": start,
        "dt_s": DT,
        "channels": list(FEATURE_CHANNELS),
        "physical_slots": {
            "accel_xyz": ACC_XYZ_IDX.tolist(),
            "gyro_xyz": GYRO_XYZ_IDX.tolist(),
            "gravity_xyz": GRAV_XYZ_IDX.tolist(),
        },
        "assert_channels": sorted(set(range(len(FEATURE_CHANNELS)))
                                  - set(GRAV_XYZ_IDX.tolist())),
        "gravity_note": "Slots 6-8 hold the phone dataset's GRAVITY column in "
                        "training and the engine's causal estimate at runtime; "
                        "check the norm is near 9.8, not equality.",
        "tolerance": 2e-4,
        # Flat [n*3] arrays: the C++ test reads these with a few lines of
        # string scanning rather than taking a JSON dependency for one fixture.
        "accel_flat": [round(float(v), 9) for v in accel.reshape(-1)],
        "gyro_flat": [round(float(v), 9) for v in gyro.reshape(-1)],
        "expected_features": [[round(float(v), 9) for v in expected[k]]
                              for k in range(n)],
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--run", type=Path, default=None,
                    help="processed .npz to sample from (default: first)")
    ap.add_argument("--n", type=int, default=N_SAMPLES)
    ap.add_argument("--start", type=int, default=0)
    ap.add_argument("--out", type=Path, default=OUT_PATH)
    args = ap.parse_args(argv)

    run = args.run or next(iter(sorted(PROC_DIR.glob("*.npz"))), None)
    if run is None:
        print("no processed runs; run prepare first")
        return 1

    fixture = build(run, args.n, args.start)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(fixture, indent=1) + "\n")
    print(f"{args.n} samples from {fixture['source_run']} -> {args.out}")
    print(f"asserted channels: {fixture['assert_channels']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
