// Pins ModelWindow's tensor against the training pipeline that produced the
// model, using a fixture generated by `python -m driftless_train.edge_fixture`.
//
// Why this exists: the model accepts any 14xN float tensor and returns three
// plausible numbers for it. A channel in the wrong slot is not an error, it is
// confident nonsense -- so "it runs and the outputs are finite" proves nothing
// about the layout. Only comparing against the pipeline's own derived features
// does.

#include "driftless/model_window.h"

#include <gtest/gtest.h>

#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

// Minimal extraction from the fixture. Deliberately not a JSON library: the
// file is generated by us in a fixed shape, and adding a dependency to read
// one array of numbers is a poor trade.
std::vector<double> numbersInBlock(const std::string& text, const std::string& key,
                                   std::size_t start_from = 0) {
    const auto key_pos = text.find("\"" + key + "\"", start_from);
    if (key_pos == std::string::npos) return {};
    const auto open = text.find('[', key_pos);
    if (open == std::string::npos) return {};
    int depth = 0;
    std::size_t close = open;
    for (std::size_t i = open; i < text.size(); ++i) {
        if (text[i] == '[') ++depth;
        if (text[i] == ']' && --depth == 0) { close = i; break; }
    }
    std::vector<double> out;
    std::string body = text.substr(open + 1, close - open - 1);
    for (char& c : body) if (c == '[' || c == ']' || c == ',') c = ' ';
    std::istringstream is(body);
    double v;
    while (is >> v) out.push_back(v);
    return out;
}

std::string fixtureText() {
    // Ships with the model, not with these tests: the Android app asserts
    // against the same file, so it belongs beside MODEL_CONTRACT.md rather
    // than inside one consumer's test directory.
    const std::string path =
        std::string(DRIFTLESS_MODEL_DIR) + "/model_window_golden.json";
    std::ifstream f(path);
    if (!f.good()) return {};
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

constexpr int kCh = driftless::ModelWindow::kChannels;

}  // namespace

TEST(ModelWindowGolden, ChannelLayoutMatchesTheTrainingPipeline) {
    const std::string text = fixtureText();
    if (text.empty()) {
        GTEST_SKIP() << "model_window_golden.json missing -- run `cd training "
                        "&& python -m driftless_train.edge_fixture && python "
                        "export/to_tflite.py --copy-to-consumers`";
    }

    // Flat [n*3] accel and gyro, and flat [n*14] expected feature rows.
    const std::vector<double> accel = numbersInBlock(text, "accel_flat");
    const std::vector<double> gyro = numbersInBlock(text, "gyro_flat");
    const std::vector<double> expected = numbersInBlock(text, "expected_features");
    const std::vector<double> assert_ch = numbersInBlock(text, "assert_channels");
    ASSERT_FALSE(accel.empty()) << "fixture has no accel_flat block";
    ASSERT_EQ(accel.size(), gyro.size());
    const std::size_t n = accel.size() / 3;
    ASSERT_EQ(expected.size(), n * static_cast<std::size_t>(kCh));

    driftless::ModelWindow window;
    std::optional<driftless::ModelWindow::Tensor> tensor;
    for (std::size_t k = 0; k < n; ++k) {
        driftless::ImuSample s;
        s.timestamp_nanos = static_cast<std::int64_t>(k) * 100'000'000;  // 10 Hz
        s.accel = driftless::Vec3(accel[k * 3], accel[k * 3 + 1], accel[k * 3 + 2]);
        s.gyro = driftless::Vec3(gyro[k * 3], gyro[k * 3 + 1], gyro[k * 3 + 2]);
        tensor = window.push(s);
    }
    ASSERT_TRUE(tensor.has_value()) << "no tensor after " << n << " samples";

    // The tensor holds the LAST kTimesteps rows, so line it up with the tail
    // of the fixture.
    const std::size_t offset = n - driftless::ModelWindow::kTimesteps;

    for (double ch_d : assert_ch) {
        const int c = static_cast<int>(ch_d);
        double worst = 0.0;
        int worst_t = -1;
        for (int t = 0; t < driftless::ModelWindow::kTimesteps; ++t) {
            const double got = (*tensor)[c * driftless::ModelWindow::kTimesteps + t];
            const double want = expected[(offset + static_cast<std::size_t>(t)) * kCh + c];
            const double d = std::abs(got - want);
            if (d > worst) { worst = d; worst_t = t; }
        }
        EXPECT_LT(worst, 2e-4)
            << "channel " << c << " disagrees with the training pipeline "
            << "(worst at t=" << worst_t << ", delta " << worst << "). "
            << "If this is a gyro slot, note physical x/y/z map to feature "
            << "slots 3/5/4, not 3/4/5 -- see driftless_train.edge_fixture.";
    }
}

TEST(ModelWindowGolden, GravityChannelsArePhysicallyPlausible) {
    const std::string text = fixtureText();
    if (text.empty()) GTEST_SKIP() << "fixture missing";

    const std::vector<double> accel = numbersInBlock(text, "accel_flat");
    const std::vector<double> gyro = numbersInBlock(text, "gyro_flat");
    ASSERT_FALSE(accel.empty());
    const std::size_t n = accel.size() / 3;

    driftless::ModelWindow window;
    std::optional<driftless::ModelWindow::Tensor> tensor;
    for (std::size_t k = 0; k < n; ++k) {
        driftless::ImuSample s;
        s.timestamp_nanos = static_cast<std::int64_t>(k) * 100'000'000;
        s.accel = driftless::Vec3(accel[k * 3], accel[k * 3 + 1], accel[k * 3 + 2]);
        s.gyro = driftless::Vec3(gyro[k * 3], gyro[k * 3 + 1], gyro[k * 3 + 2]);
        tensor = window.push(s);
    }
    ASSERT_TRUE(tensor.has_value());

    // Slots 6-8 are the attitude estimate, not bit-comparable with training's
    // GRAVITY column, so assert the physics instead: a gravity vector.
    const int T = driftless::ModelWindow::kTimesteps;
    for (int t = 0; t < T; ++t) {
        const double gx = (*tensor)[6 * T + t];
        const double gy = (*tensor)[7 * T + t];
        const double gz = (*tensor)[8 * T + t];
        const double norm = std::sqrt(gx * gx + gy * gy + gz * gz);
        EXPECT_GT(norm, 9.0) << "gravity estimate too small at t=" << t;
        EXPECT_LT(norm, 10.6) << "gravity estimate too large at t=" << t;
    }
}
