"""Export a trained checkpoint for both runtimes.

  TFLite -> the Android app  (android/app/src/main/assets/models/)
  ONNX   -> the C++ edge engine (edge-engine/)

IMPORTANT correction to the original plan in this file, which said
"PyTorch -> ONNX -> TFLite, via onnx2tf":

**onnx2tf does not work for this architecture.** Bisecting the graph showed the
residual connection is the culprit -- a block without `x + y` converts, and with
it the TFLite graph fails to prepare ("num_input_elements != num_output_elements
(3936 != 3)", where 3936 = 48x82 is a padded intermediate). Worse, a variant that
DID convert disagreed with PyTorch by 5.4e-2 while reporting success, which is the
dangerous kind of failure: it would have shipped a silently wrong model.

So TFLite is produced by rebuilding the network with Keras layers and porting the
trained weights across, then using the first-party Keras -> TFLite converter.
That matches PyTorch to ~1e-6. See driftless_train/keras_port.py for the
bisection and two further traps (Keras GroupNormalization defaults to
epsilon=1e-3 vs PyTorch's 1e-5; tf.lite.Optimize.DEFAULT silently applies int8
weight quantisation worth 2-8% error).

This file is a thin wrapper so the documented entry point keeps working:

    python -m driftless_train.export          # equivalent, more options
    python export/to_tflite.py --copy-to-consumers
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from driftless_train.export import main as export_main  # noqa: E402
from driftless_train.paths import (  # noqa: E402
    ANDROID_ASSETS_DIR,
    EDGE_MODELS_DIR,
    MODEL_DIR,
)

# The consumers' own stubs name the file they load: VelocityModel.kt looks for
# `assets/models/velocity_model.tflite` and velocity_model.h wraps the matching
# .onnx. Copy to THOSE names rather than the training-side ones, so their code
# works as written instead of failing on a path only this repo knows.
CONSUMER_NAMES = (
    ("tcn_speed_heading.tflite", "velocity_model.tflite", "ANDROID"),
    ("tcn_speed_heading.onnx", "velocity_model.onnx", "EDGE"),
)


def copy_to_consumers() -> None:
    """Place the exports where the Android and edge-engine builds look for them."""
    dests = {"ANDROID": ANDROID_ASSETS_DIR, "EDGE": EDGE_MODELS_DIR}
    for src_name, dest_name, which in CONSUMER_NAMES:
        src = MODEL_DIR / src_name
        if not src.exists():
            print(f"missing {src_name}; run the export first")
            continue
        dest_dir = dests[which]
        dest_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest_dir / dest_name)
        print(f"{src_name} -> {dest_dir / dest_name}")

    # A stray sidecar from an older export would be loaded in preference to
    # nothing and silently shadow the current weights -- delete it.
    for stale in (EDGE_MODELS_DIR / "tcn_speed_heading.onnx.data",
                  EDGE_MODELS_DIR / "velocity_model.onnx.data"):
        if stale.exists():
            stale.unlink()
            print(f"removed stale sidecar {stale.name}")

    # Next to the files themselves, in both trees -- the contract is about both
    # runtimes and whoever opens one directory should find it there.
    for dest_dir in dests.values():
        contract = dest_dir / "MODEL_CONTRACT.md"
        contract.parent.mkdir(parents=True, exist_ok=True)
        contract.write_text(MODEL_CONTRACT)
        print(f"contract -> {contract}")


MODEL_CONTRACT = """\
# velocity_model — input/output contract

Generated by `training/export/to_tflite.py --copy-to-consumers`. Do not edit.

**One checkpoint, two runtimes.** Same weights, different tensor layout.

| runtime | file | input | output |
|---|---|---|---|
| Android (TFLite) | `assets/models/velocity_model.tflite` | `[1,80,14]` NWC | `[1,3]` |
| Edge (ONNX) | `models/velocity_model.onnx` | `[1,14,80]` NCW | `[1,3]` |

All tensors are float32. TFLite is time-major (channels-last).

Note the layouts differ. TFLite is channels-last, which is the natural layout
for an Android ring buffer; ONNX is channels-first. Feeding one layout to the
other runtime will not error, it will just return nonsense.

## The output is THREE values, not one

    output[0] = speed_ms    mean forward speed over the interval, m/s
    output[1] = dpsi_rad    heading change across the interval, radians
    output[2] = dv_ms       change in speed across the interval, m/s

`VelocityModel.kt`'s `-> Float` and any single-output assumption are wrong: the
model has a 3-element output and reading only `output[0]` throws away the
heading-change measurement, which is the more accurate of the two.

## Window

14 channels, 80 samples at 10 Hz = **8 s of causal context**, and the prediction
covers the final **2 s** (20 samples) of that window. Channel order is
`IMU_CHANNELS + DERIVED_CHANNELS` from `training/driftless_train/preprocess.py`;
the five derived channels are computed by `imu_derived()` and must be recomputed
on-device, not zero-filled.

Input normalisation and output de-normalisation are constant buffers **inside**
the graph. Feed raw SI units (m/s^2, rad/s) and read SI units out; do not
normalise on either side.

## How this file got here, and how to refresh it

These two model files are **not committed** -- `.gitignore` keeps binaries out
of the tree except the single canonical copy under
`training/artifacts/models/`. A fresh clone will NOT have them.

**What actually happens without them is worse than a failure: nothing.** The
edge engine's `test_velocity_model` SKIPS when the `.onnx` is absent, so `ctest`
reports success with the model never loaded, and a CI gate reading the exit code
scores that as coverage of the inference path. Treat a green run as meaningless
for this model unless you have confirmed the file was present.

To place them:

    cd training && export PYTHONPATH=.
    python export/to_tflite.py --copy-to-consumers

That re-exports from the checkpoint, re-verifies numerical parity against
PyTorch, copies both runtimes into place and rewrites this file. Wire it into
the app/engine build step rather than copying by hand.

## Weights are inline

Each file is self-contained. There is no `.onnx.data` sidecar -- an earlier
export produced one and it was a deployment trap, since its filename was
recorded inside the `.onnx`.
"""


if __name__ == "__main__":
    argv = [a for a in sys.argv[1:] if a != "--copy-to-consumers"]
    rc = export_main(argv)
    if "--copy-to-consumers" in sys.argv[1:]:
        copy_to_consumers()
    raise SystemExit(rc)
