package com.driftless.fusion

/**
 * TFLite wrapper for the learned speed/heading model trained offline on
 * IO-VNBD (see training/). Takes a windowed IMU segment; this is what stands
 * in for the OBD-II speed feed we don't have.
 *
 * CONTRACT (see assets/models/MODEL_CONTRACT.md, generated by the export):
 *   input   [1, 80, 14] float32, channels-LAST (time-major, natural for a
 *           ring buffer). 80 samples at 10 Hz = 8 s of causal context; the
 *           prediction covers the final 2 s.
 *   output  [1, 3] float32 — NOT a single Float:
 *             [0] speed_ms   mean forward speed over the interval, m/s
 *             [1] dpsi_rad   heading change across the interval, rad
 *             [2] dv_ms      change in speed across the interval, m/s
 *
 * Normalisation is baked into the graph: feed raw SI units, read SI units.
 * The 14 channels are 9 raw IMU axes plus 5 gravity-projected derived
 * channels, which must be computed on-device (imu_derived in
 * training/driftless_train/preprocess.py) — zero-filling them will not error,
 * it will just return nonsense.
 */
class VelocityModel {
    // TODO: load assets/models/velocity_model.tflite,
    //       Interpreter.run(window) -> FloatArray(3), see contract above
}
